// This file is generated by next-typesafe-url
// Do not edit this file directly.

// @generated
// prettier-ignore
/* eslint-disable */

declare module "@@@next-typesafe-url" {
  import type { InferRoute, StaticRoute } from "next-typesafe-url";

  interface DynamicRouter {
    "/bobbleheads/add": InferRoute<import("./src/app/(app)/bobbleheads/add/route-type").RouteType>;
    "/bobbleheads/[bobbleheadId]": InferRoute<import("./src/app/(app)/bobbleheads/[bobbleheadId]/(bobblehead)/route-type").RouteType>;
    "/bobbleheads/[bobbleheadId]/edit": InferRoute<import("./src/app/(app)/bobbleheads/[bobbleheadId]/edit/route-type").RouteType>;
    "/browse/categories/[category]": InferRoute<import("./src/app/(app)/browse/categories/[category]/route-type").RouteType>;
    "/browse/search": InferRoute<import("./src/app/(app)/browse/search/route-type").RouteType>;
    "/collections/[collectionId]": InferRoute<import("./src/app/(app)/collections/[collectionId]/(collection)/route-type").RouteType>;
    "/collections/[collectionId]/subcollection/[subcollectionId]": InferRoute<import("./src/app/(app)/collections/[collectionId]/subcollection/[subcollectionId]/route-type").RouteType>;
    "/dashboard/collection": InferRoute<import("./src/app/(app)/dashboard/collection/(collection)/route-type").RouteType>;
    "/users/[userId]": InferRoute<import("./src/app/(app)/users/[userId]/route-type").RouteType>;
  }

  interface StaticRouter {
    "/": StaticRoute;
    "/admin/analytics": StaticRoute;
    "/admin/featured-content": StaticRoute;
    "/admin/launch-notifications": StaticRoute;
    "/admin": StaticRoute;
    "/admin/reports": StaticRoute;
    "/admin/users": StaticRoute;
    "/browse/categories": StaticRoute;
    "/browse/featured": StaticRoute;
    "/browse": StaticRoute;
    "/browse/trending": StaticRoute;
    "/collections/[collectionId]/edit": StaticRoute;
    "/collections/[collectionId]/settings": StaticRoute;
    "/collections/[collectionId]/share": StaticRoute;
    "/dashboard/feed": StaticRoute;
    "/dashboard/notifications": StaticRoute;
    "/settings/collections": StaticRoute;
    "/settings/data/export": StaticRoute;
    "/settings/data/import": StaticRoute;
    "/settings/notifications": StaticRoute;
    "/settings": StaticRoute;
    "/settings/privacy": StaticRoute;
    "/settings/profile": StaticRoute;
    "/users/[userId]/collections": StaticRoute;
    "/users/[userId]/followers": StaticRoute;
    "/users/[userId]/following": StaticRoute;
    "/about": StaticRoute;
    "/coming-soon": StaticRoute;
    "/privacy": StaticRoute;
    "/terms": StaticRoute;
    "/examples/ably": StaticRoute;
    "/examples/sentry": StaticRoute;
  }
}
