// This file is generated by next-typesafe-url
// Do not edit this file directly.

// @generated
// prettier-ignore
/* eslint-disable */

declare module "@@@next-typesafe-url" {
  import type { InferRoute, StaticRoute } from "next-typesafe-url";

  interface DynamicRouter {
    "/browse/categories/[category]": InferRoute<import("./src/app/(app)/browse/categories/[category]/route-type").RouteType>;
    "/browse/search": InferRoute<import("./src/app/(app)/browse/search/route-type").RouteType>;
    "/dashboard/collection": InferRoute<import("./src/app/(app)/dashboard/collection/(collection)/route-type").RouteType>;
    "/user/[username]/collection/[collectionSlug]/bobbleheads/[bobbleheadSlug]": InferRoute<import("./src/app/(app)/user/[username]/collection/[collectionSlug]/bobbleheads/[bobbleheadSlug]/route-type").RouteType>;
    "/user/[username]/collection/[collectionSlug]": InferRoute<import("./src/app/(app)/user/[username]/collection/[collectionSlug]/route-type").RouteType>;
    "/users/profile/[userId]": InferRoute<import("./src/app/(app)/users/profile/[userId]/route-type").RouteType>;
  }

  interface StaticRouter {
    "/": StaticRoute;
    "/admin/analytics": StaticRoute;
    "/admin/featured-content": StaticRoute;
    "/admin/launch-notifications": StaticRoute;
    "/admin": StaticRoute;
    "/admin/reports": StaticRoute;
    "/admin/users": StaticRoute;
    "/browse/categories": StaticRoute;
    "/browse/featured": StaticRoute;
    "/browse": StaticRoute;
    "/browse/trending": StaticRoute;
    "/settings/collections": StaticRoute;
    "/settings/data/export": StaticRoute;
    "/settings/data/import": StaticRoute;
    "/settings/notifications": StaticRoute;
    "/settings": StaticRoute;
    "/settings/privacy": StaticRoute;
    "/settings/profile": StaticRoute;
    "/about": StaticRoute;
    "/coming-soon": StaticRoute;
    "/privacy": StaticRoute;
    "/terms": StaticRoute;
  }
}
