/**
 * error codes used throughout the application for consistent error identification
 * these are internal codes used for logging and debugging
 */
export const ERROR_CODES = {
  ADMIN: {
    CREATE_FEATURED_CONTENT_FAILED: 'ADMIN_CREATE_FEATURED_CONTENT_FAILED',
    DELETE_FEATURED_CONTENT_FAILED: 'ADMIN_DELETE_FEATURED_CONTENT_FAILED',
    FEATURED_CONTENT_NOT_FOUND: 'ADMIN_FEATURED_CONTENT_NOT_FOUND',
    INSUFFICIENT_PRIVILEGES: 'ADMIN_INSUFFICIENT_PRIVILEGES',
    TOGGLE_FEATURED_CONTENT_FAILED: 'ADMIN_TOGGLE_FEATURED_CONTENT_FAILED',
    UPDATE_FEATURED_CONTENT_FAILED: 'ADMIN_UPDATE_FEATURED_CONTENT_FAILED',
  },
  ANALYTICS: {
    BATCH_VIEW_RECORD_FAILED: 'ANALYTICS_BATCH_VIEW_RECORD_FAILED',
    VIEW_AGGREGATION_FAILED: 'ANALYTICS_VIEW_AGGREGATION_FAILED',
    VIEW_RECORD_FAILED: 'ANALYTICS_VIEW_RECORD_FAILED',
  },
  BOBBLEHEADS: {
    CREATE_FAILED: 'BOBBLEHEAD_CREATE_FAILED',
    DELETE_FAILED: 'BOBBLEHEAD_DELETE_FAILED',
    INVALID_OWNER: 'BOBBLEHEAD_INVALID_OWNER',
    NOT_FOUND: 'BOBBLEHEAD_NOT_FOUND',
    PHOTO_CLOUDINARY_CLEANUP_FAILED: 'BOBBLEHEAD_PHOTO_CLOUDINARY_CLEANUP_FAILED',
    PHOTO_DELETE_FAILED: 'BOBBLEHEAD_PHOTO_DELETE_FAILED',
    PHOTO_UPLOAD_FAILED: 'BOBBLEHEAD_PHOTO_UPLOAD_FAILED',
    UPDATE_FAILED: 'BOBBLEHEAD_UPDATE_FAILED',
  },
  COLLECTIONS: {
    CREATE_FAILED: 'COLLECTION_CREATE_FAILED',
    DELETE_FAILED: 'COLLECTION_DELETE_FAILED',
    EXISTING_NOT_FOUND: 'EXISTING_COLLECTION_NOT_FOUND',
    EXISTING_UPDATE_FAILED: 'EXISTING_COLLECTION_UPDATE_FAILED',
    INVALID_OWNER: 'COLLECTION_INVALID_OWNER',
    NOT_FOUND: 'COLLECTION_NOT_FOUND',
    NOT_PUBLIC: 'COLLECTION_NOT_PUBLIC',
    UPDATE_FAILED: 'COLLECTION_UPDATE_FAILED',
  },
  COMMENTS: {
    COMMENT_DELETE_FAILED: 'COMMENT_DELETE_FAILED',
    COMMENT_EDIT_WINDOW_EXPIRED: 'COMMENT_EDIT_WINDOW_EXPIRED',
    COMMENT_FAILED: 'COMMENT_FAILED',
    COMMENT_NOT_FOUND: 'COMMENT_NOT_FOUND',
    COMMENT_UPDATE_FAILED: 'COMMENT_UPDATE_FAILED',
    UNAUTHORIZED_COMMENT_ACCESS: 'UNAUTHORIZED_COMMENT_ACCESS',
  },
  CONTENT_REPORTS: {
    CREATE_FAILED: 'CONTENT_REPORT_CREATE_FAILED',
    DUPLICATE_REPORT: 'CONTENT_REPORT_DUPLICATE',
    INVALID_TARGET: 'CONTENT_REPORT_INVALID_TARGET',
    NOT_FOUND: 'CONTENT_REPORT_NOT_FOUND',
    RATE_LIMIT_EXCEEDED: 'CONTENT_REPORT_RATE_LIMIT_EXCEEDED',
    SELF_REPORT: 'CONTENT_REPORT_SELF_REPORT',
    TARGET_NOT_FOUND: 'CONTENT_REPORT_TARGET_NOT_FOUND',
    UPDATE_FAILED: 'CONTENT_REPORT_UPDATE_FAILED',
  },
  FEATURE_PLANNER: {
    REFINEMENT_FAILED: 'FEATURE_PLANNER_REFINEMENT_FAILED',
    REFINEMENT_TIMEOUT: 'FEATURE_PLANNER_REFINEMENT_TIMEOUT',
    REFINEMENT_TOO_SHORT: 'FEATURE_PLANNER_REFINEMENT_TOO_SHORT',
    SDK_ERROR: 'FEATURE_PLANNER_SDK_ERROR',
  },
  FEATURED_CONTENT: {
    CREATE_FAILED: 'FEATURED_CONTENT_CREATE_FAILED',
    DELETE_FAILED: 'FEATURED_CONTENT_DELETE_FAILED',
    NOT_FOUND: 'FEATURED_CONTENT_NOT_FOUND',
    TOGGLE_FAILED: 'FEATURED_CONTENT_TOGGLE_FAILED',
    UPDATE_FAILED: 'FEATURED_CONTENT_UPDATE_FAILED',
  },
  SEARCH: {
    INVALID_QUERY: 'SEARCH_INVALID_QUERY',
    NO_RESULTS: 'SEARCH_NO_RESULTS',
    SERVICE_ERROR: 'SEARCH_SERVICE_ERROR',
  },
  SOCIAL: {
    LIKE_FAILED: 'SOCIAL_LIKE_FAILED',
    UNLIKE_FAILED: 'SOCIAL_UNLIKE_FAILED',
  },
  SUBCOLLECTIONS: {
    CREATE_FAILED: 'SUBCOLLECTION_CREATE_FAILED',
    DELETE_FAILED: 'SUBCOLLECTION_DELETE_FAILED',
    NOT_FOUND: 'SUBCOLLECTION_NOT_FOUND',
    UPDATE_FAILED: 'SUBCOLLECTION_UPDATE_FAILED',
  },
  TAGS: {
    ATTACH_FAILED: 'TAG_ATTACH_FAILED',
    CREATE_FAILED: 'TAG_CREATE_FAILED',
    DELETE_FAILED: 'TAG_DELETE_FAILED',
    DETACH_FAILED: 'TAG_DETACH_FAILED',
    LIMIT_EXCEEDED: 'TAG_LIMIT_EXCEEDED',
    NOT_FOUND: 'TAG_NOT_FOUND',
    UPDATE_FAILED: 'TAG_UPDATE_FAILED',
  },
  USERS: {
    DELETE_FAILED: 'USER_DELETE_FAILED',
    INSUFFICIENT_PRIVILEGES: 'USER_INSUFFICIENT_PRIVILEGES',
    NOT_FOUND: 'USER_NOT_FOUND',
    UPDATE_FAILED: 'USER_UPDATE_FAILED',
    USERNAME_CHANGE_COOLDOWN: 'USER_USERNAME_CHANGE_COOLDOWN',
    USERNAME_RESERVED: 'USER_USERNAME_RESERVED',
    USERNAME_TAKEN: 'USER_USERNAME_TAKEN',
    USERNAME_UPDATE_FAILED: 'USER_USERNAME_UPDATE_FAILED',
  },
} as const;

export type ErrorCode =
  (typeof ERROR_CODES)[keyof typeof ERROR_CODES][keyof (typeof ERROR_CODES)[keyof typeof ERROR_CODES]];

export const getErrorCode = <T extends keyof typeof ERROR_CODES>(
  category: T,
  code: keyof (typeof ERROR_CODES)[T],
): string => {
  return ERROR_CODES[category][code] as string;
};
