/**
 * error codes used throughout the application for consistent error identification
 * these are internal codes used for logging and debugging
 */
export const ERROR_CODES = {
  BOBBLEHEADS: {
    CREATE_FAILED: 'BOBBLEHEAD_CREATE_FAILED',
    DELETE_FAILED: 'BOBBLEHEAD_DELETE_FAILED',
    INVALID_OWNER: 'BOBBLEHEAD_INVALID_OWNER',
    NOT_FOUND: 'BOBBLEHEAD_NOT_FOUND',
    PHOTO_DELETE_FAILED: 'BOBBLEHEAD_PHOTO_DELETE_FAILED',
    PHOTO_UPLOAD_FAILED: 'BOBBLEHEAD_PHOTO_UPLOAD_FAILED',
    UPDATE_FAILED: 'BOBBLEHEAD_UPDATE_FAILED',
  },
  COLLECTIONS: {
    CREATE_FAILED: 'COLLECTION_CREATE_FAILED',
    DELETE_FAILED: 'COLLECTION_DELETE_FAILED',
    EXISTING_NOT_FOUND: 'EXISTING_COLLECTION_NOT_FOUND',
    EXISTING_UPDATE_FAILED: 'EXISTING_COLLECTION_UPDATE_FAILED',
    INVALID_OWNER: 'COLLECTION_INVALID_OWNER',
    NOT_FOUND: 'COLLECTION_NOT_FOUND',
    NOT_PUBLIC: 'COLLECTION_NOT_PUBLIC',
    UPDATE_FAILED: 'COLLECTION_UPDATE_FAILED',
  },
  FEATURED_CONTENT: {
    CREATE_FAILED: 'FEATURED_CONTENT_CREATE_FAILED',
    DELETE_FAILED: 'FEATURED_CONTENT_DELETE_FAILED',
    NOT_FOUND: 'FEATURED_CONTENT_NOT_FOUND',
    TOGGLE_FAILED: 'FEATURED_CONTENT_TOGGLE_FAILED',
    UPDATE_FAILED: 'FEATURED_CONTENT_UPDATE_FAILED',
  },
  SEARCH: {
    INVALID_QUERY: 'SEARCH_INVALID_QUERY',
    NO_RESULTS: 'SEARCH_NO_RESULTS',
    SERVICE_ERROR: 'SEARCH_SERVICE_ERROR',
  },
  SUBCOLLECTIONS: {
    CREATE_FAILED: 'SUBCOLLECTION_CREATE_FAILED',
    DELETE_FAILED: 'SUBCOLLECTION_DELETE_FAILED',
    NOT_FOUND: 'SUBCOLLECTION_NOT_FOUND',
    UPDATE_FAILED: 'SUBCOLLECTION_UPDATE_FAILED',
  },
  USERS: {
    DELETE_FAILED: 'USER_DELETE_FAILED',
    INSUFFICIENT_PRIVILEGES: 'USER_INSUFFICIENT_PRIVILEGES',
    NOT_FOUND: 'USER_NOT_FOUND',
    UPDATE_FAILED: 'USER_UPDATE_FAILED',
  },
} as const;

export type ErrorCode =
  (typeof ERROR_CODES)[keyof typeof ERROR_CODES][keyof (typeof ERROR_CODES)[keyof typeof ERROR_CODES]];

export const getErrorCode = <T extends keyof typeof ERROR_CODES>(
  category: T,
  code: keyof (typeof ERROR_CODES)[T],
): string => {
  return ERROR_CODES[category][code] as string;
};
