/**
 * operation names used in error handling and logging throughout the application
 * centralized for consistency and maintainability
 */
export const OPERATIONS = {
  ADMIN: {
    BULK_UPDATE_REPORTS: 'admin_bulk_update_reports',
    CREATE_FEATURED_CONTENT: 'admin_create_featured_content',
    DELETE_FEATURED_CONTENT: 'admin_delete_featured_content',
    GET_ADMIN_REPORTS: 'admin_get_reports',
    GET_FEATURED_CONTENT_BY_ID: 'admin_get_featured_content_by_id',
    GET_REPORTS_STATS: 'admin_get_reports_stats',
    TOGGLE_FEATURED_CONTENT_ACTIVE: 'admin_toggle_featured_content_active',
    TOGGLE_FEATURED_CONTENT_STATUS: 'admin_toggle_featured_content_status',
    UPDATE_FEATURED_CONTENT: 'admin_update_featured_content',
    UPDATE_REPORT_STATUS: 'admin_update_report_status',
  },
  ADMIN_USERS: {
    GET_USER_DETAILS: 'admin_get_user_details',
    GET_USER_STATS: 'admin_get_user_stats',
    GET_USERS: 'admin_get_users',
    LOCK_USER: 'admin_lock_user',
    UNLOCK_USER: 'admin_unlock_user',
    UPDATE_USER_ROLE: 'admin_update_user_role',
    VERIFY_USER_EMAIL: 'admin_verify_user_email',
  },
  ANALYTICS: {
    AGGREGATE_VIEWS: 'aggregate_views',
    BATCH_RECORD_VIEWS: 'batch_record_views',
    GET_TRENDING_CONTENT: 'get_trending_content',
    GET_VIEW_STATS: 'get_view_stats',
    RECORD_VIEW: 'record_view',
  },
  BOBBLEHEADS: {
    CREATE: 'create_bobblehead',
    CREATE_WITH_PHOTOS: 'create_bobblehead_with_photos',
    DELETE: 'delete_bobblehead',
    DELETE_PHOTO: 'delete_bobblehead_photo',
    DELETE_WITH_PHOTOS: 'delete_bobblehead_with_photos',
    FIND_BY_COLLECTION: 'find_bobbleheads_by_collection',
    GET_BY_USER: 'get_bobbleheads_by_user',
    GET_PHOTOS: 'get_bobblehead_photos',
    REORDER_PHOTOS: 'reorder_bobblehead_photos',
    SEARCH: 'search_bobbleheads',
    UPDATE: 'update_bobblehead',
    UPDATE_PHOTO_METADATA: 'update_bobblehead_photo_metadata',
    UPLOAD_PHOTO: 'upload_bobblehead_photo',
  },
  COLLECTIONS: {
    BROWSE: 'browse_collections',
    BROWSE_CATEGORIES: 'browse_categories',
    CREATE: 'create_collection',
    DELETE: 'delete_collection',
    GET_BY_USER: 'get_collections_by_user',
    GET_CATEGORIES: 'get_categories',
    UPDATE: 'update_collection',
  },
  COMMENTS: {
    CREATE_COMMENT: 'create_comment',
    DELETE_COMMENT: 'delete_comment',
    GET_COMMENT_COUNT: 'get_comment_count',
    GET_COMMENTS: 'get_comments',
    UPDATE_COMMENT: 'update_comment',
  },
  FEATURED_CONTENT: {
    CREATE: 'create_featured_content',
    DELETE: 'delete_featured_content',
    GET_BY_ID: 'get_featured_content_by_id',
    TOGGLE_ACTIVE: 'toggle_featured_content_active',
    TOGGLE_STATUS: 'toggle_featured_content_status',
    UPDATE: 'update_featured_content',
  },
  MODERATION: {
    CHECK_EXISTING_REPORT: 'check_existing_report',
    CHECK_RATE_LIMIT: 'check_rate_limit',
    CREATE_REPORT: 'create_content_report',
    GET_REPORT_STATUS: 'get_report_status',
    VALIDATE_REPORT_TARGET: 'validate_report_target',
  },
  NEWSLETTER: {
    CHECK_SUBSCRIPTION: 'check_newsletter_subscription',
    SEND_WELCOME_EMAIL: 'send_newsletter_welcome_email',
    SUBSCRIBE: 'subscribe_to_newsletter',
    UNSUBSCRIBE: 'unsubscribe_from_newsletter',
  },
  NEWSLETTER_ADMIN: {
    ADMIN_UNSUBSCRIBE_USER: 'admin_unsubscribe_user',
    CREATE_NEWSLETTER_TEMPLATE: 'create_newsletter_template',
    DELETE_NEWSLETTER_TEMPLATE: 'delete_newsletter_template',
    GET_NEWSLETTER_SEND_HISTORY: 'get_newsletter_send_history',
    GET_NEWSLETTER_STATS: 'get_newsletter_stats',
    GET_NEWSLETTER_SUBSCRIBERS: 'get_newsletter_subscribers',
    GET_NEWSLETTER_TEMPLATES: 'get_newsletter_templates',
    SEND_NEWSLETTER_BULK: 'send_newsletter_bulk',
    UPDATE_NEWSLETTER_TEMPLATE: 'update_newsletter_template',
  },
  SEARCH: {
    BOBBLEHEADS: 'search_bobbleheads',
    COLLECTIONS: 'search_collections',
    USERS: 'search_users',
  },
  SOCIAL: {
    CREATE_LIKE: 'create_like',
    DELETE_LIKE: 'delete_like',
    GET_LIKE_COUNT: 'get_like_count',
    GET_LIKE_COUNTS: 'get_like_counts',
    GET_RECENT_LIKES: 'get_recent_likes',
    GET_TRENDING_CONTENT: 'get_trending_content',
    GET_USER_LIKE_STATUS: 'get_user_like_status',
    GET_USER_LIKE_STATUSES: 'get_user_like_statuses',
    TOGGLE_LIKE: 'toggle_like',
  },
  SUBCOLLECTIONS: {
    CREATE: 'create_subcollection',
    CREATE_ALT: 'create_sub_collection',
    DELETE: 'delete_subcollection',
    GET: 'get_sub_collections',
    UPDATE: 'update_subcollection',
  },
  TAGS: {
    ADD: 'add_tag',
    ATTACH_TO_BOBBLEHEAD: 'attach_tags_to_bobblehead',
    BULK_DELETE: 'bulk_delete_tags',
    CREATE: 'create_tag',
    DELETE: 'delete_tag',
    DETACH_FROM_BOBBLEHEAD: 'detach_tags_from_bobblehead',
    GET_OR_CREATE: 'get_or_create_tag',
    GET_STATS: 'get_tag_stats',
    MERGE: 'merge_tags',
    REMOVE: 'remove_tag',
    REMOVE_ALL_FROM_BOBBLEHEAD: 'remove_all_tags_from_bobblehead',
    SEARCH: 'search_tags',
    UPDATE: 'update_tag',
    VALIDATE: 'validate_tags',
  },
  USERS: {
    DELETE_ACCOUNT: 'delete_user_account',
    UPDATE_PROFILE: 'update_user_profile',
    UPDATE_SETTINGS: 'update_user_settings',
  },
} as const;

export type Operation =
  (typeof OPERATIONS)[keyof typeof OPERATIONS][keyof (typeof OPERATIONS)[keyof typeof OPERATIONS]];

export const getOperationName = <T extends keyof typeof OPERATIONS>(
  category: T,
  operation: keyof (typeof OPERATIONS)[T],
): string => {
  return OPERATIONS[category][operation] as string;
};
