/**
 * operation names used in error handling and logging throughout the application
 * centralized for consistency and maintainability
 */
export const OPERATIONS = {
  ADMIN: {
    BULK_UPDATE_REPORTS: 'admin_bulk_update_reports',
    CREATE_FEATURED_CONTENT: 'admin_create_featured_content',
    DELETE_FEATURED_CONTENT: 'admin_delete_featured_content',
    GET_ADMIN_REPORTS: 'admin_get_reports',
    GET_FEATURED_CONTENT_BY_ID: 'admin_get_featured_content_by_id',
    GET_REPORTS_STATS: 'admin_get_reports_stats',
    TOGGLE_FEATURED_CONTENT_ACTIVE: 'admin_toggle_featured_content_active',
    TOGGLE_FEATURED_CONTENT_STATUS: 'admin_toggle_featured_content_status',
    UPDATE_FEATURED_CONTENT: 'admin_update_featured_content',
    UPDATE_REPORT_STATUS: 'admin_update_report_status',
  },
  ANALYTICS: {
    AGGREGATE_VIEWS: 'aggregate_views',
    BATCH_RECORD_VIEWS: 'batch_record_views',
    GET_TRENDING_CONTENT: 'get_trending_content',
    GET_VIEW_STATS: 'get_view_stats',
    RECORD_VIEW: 'record_view',
  },
  BOBBLEHEADS: {
    CREATE: 'create_bobblehead',
    CREATE_WITH_PHOTOS: 'create_bobblehead_with_photos',
    DELETE: 'delete_bobblehead',
    DELETE_PHOTO: 'delete_bobblehead_photo',
    DELETE_WITH_PHOTOS: 'delete_bobblehead_with_photos',
    FIND_BY_COLLECTION: 'find_bobbleheads_by_collection',
    GET_BY_USER: 'get_bobbleheads_by_user',
    GET_PHOTOS: 'get_bobblehead_photos',
    REORDER_PHOTOS: 'reorder_bobblehead_photos',
    SEARCH: 'search_bobbleheads',
    UPDATE: 'update_bobblehead',
    UPLOAD_PHOTO: 'upload_bobblehead_photo',
  },
  COLLECTIONS: {
    CREATE: 'create_collection',
    DELETE: 'delete_collection',
    GET_BY_USER: 'get_collections_by_user',
    UPDATE: 'update_collection',
  },
  FEATURE_PLANNER: {
    ADD_MANUAL_FILE: 'add_manual_file',
    CREATE_PLAN: 'create_feature_plan',
    CREATE_PLAN_STEP: 'create_plan_step',
    CREATE_REFINEMENT_AGENT: 'create_refinement_agent',
    CREATE_STEP_TEMPLATE: 'create_step_template',
    DELETE_PLAN: 'delete_feature_plan',
    DELETE_PLAN_STEP: 'delete_plan_step',
    DELETE_REFINEMENT_AGENT: 'delete_refinement_agent',
    GET_DISCOVERED_FILES: 'get_discovered_files',
    GET_EXECUTION_LOGS: 'get_execution_logs',
    GET_PLAN: 'get_feature_plan',
    GET_PLAN_GENERATIONS: 'get_plan_generations',
    GET_REFINEMENT_AGENTS: 'get_refinement_agents',
    GET_REFINEMENTS: 'get_feature_refinements',
    GET_STEP_TEMPLATES: 'get_step_templates',
    LIST_PLANS: 'list_feature_plans',
    REORDER_PLAN_STEPS: 'reorder_plan_steps',
    RUN_FILE_DISCOVERY: 'run_file_discovery',
    RUN_PLAN_GENERATION: 'run_plan_generation',
    RUN_REFINEMENT: 'run_feature_refinement',
    SELECT_FILES: 'select_discovered_files',
    SELECT_PLAN_GENERATION: 'select_plan_generation',
    SELECT_REFINEMENT: 'select_feature_refinement',
    SUGGEST_FEATURE: 'suggest_feature',
    UPDATE_PLAN: 'update_feature_plan',
    UPDATE_PLAN_STEP: 'update_plan_step',
    UPDATE_REFINEMENT_AGENT: 'update_refinement_agent',
    USE_STEP_TEMPLATE: 'use_step_template',
  },
  FEATURED_CONTENT: {
    CREATE: 'create_featured_content',
    DELETE: 'delete_featured_content',
    GET_BY_ID: 'get_featured_content_by_id',
    TOGGLE_ACTIVE: 'toggle_featured_content_active',
    TOGGLE_STATUS: 'toggle_featured_content_status',
    UPDATE: 'update_featured_content',
  },
  MODERATION: {
    CHECK_EXISTING_REPORT: 'check_existing_report',
    CHECK_RATE_LIMIT: 'check_rate_limit',
    CREATE_REPORT: 'create_content_report',
    GET_REPORT_STATUS: 'get_report_status',
    VALIDATE_REPORT_TARGET: 'validate_report_target',
  },
  SEARCH: {
    BOBBLEHEADS: 'search_bobbleheads',
    COLLECTIONS: 'search_collections',
    USERS: 'search_users',
  },
  SOCIAL: {
    CREATE_LIKE: 'create_like',
    DELETE_LIKE: 'delete_like',
    GET_LIKE_COUNT: 'get_like_count',
    GET_LIKE_COUNTS: 'get_like_counts',
    GET_RECENT_LIKES: 'get_recent_likes',
    GET_TRENDING_CONTENT: 'get_trending_content',
    GET_USER_LIKE_STATUS: 'get_user_like_status',
    GET_USER_LIKE_STATUSES: 'get_user_like_statuses',
    TOGGLE_LIKE: 'toggle_like',
  },
  SUBCOLLECTIONS: {
    CREATE: 'create_subcollection',
    CREATE_ALT: 'create_sub_collection',
    DELETE: 'delete_subcollection',
    GET: 'get_sub_collections',
    UPDATE: 'update_subcollection',
  },
  TAGS: {
    ADD: 'add_tag',
    ATTACH_TO_BOBBLEHEAD: 'attach_tags_to_bobblehead',
    BULK_DELETE: 'bulk_delete_tags',
    CREATE: 'create_tag',
    DELETE: 'delete_tag',
    DETACH_FROM_BOBBLEHEAD: 'detach_tags_from_bobblehead',
    GET_OR_CREATE: 'get_or_create_tag',
    GET_STATS: 'get_tag_stats',
    MERGE: 'merge_tags',
    REMOVE: 'remove_tag',
    REMOVE_ALL_FROM_BOBBLEHEAD: 'remove_all_tags_from_bobblehead',
    SEARCH: 'search_tags',
    UPDATE: 'update_tag',
    VALIDATE: 'validate_tags',
  },
  USERS: {
    DELETE_ACCOUNT: 'delete_user_account',
    UPDATE_PROFILE: 'update_user_profile',
    UPDATE_SETTINGS: 'update_user_settings',
  },
} as const;

export type Operation =
  (typeof OPERATIONS)[keyof typeof OPERATIONS][keyof (typeof OPERATIONS)[keyof typeof OPERATIONS]];

export const getOperationName = <T extends keyof typeof OPERATIONS>(
  category: T,
  operation: keyof (typeof OPERATIONS)[T],
): string => {
  return OPERATIONS[category][operation] as string;
};
